### ISSUE TITLE
Tag collision due to tag calculation

### ISSUE THREAD

**Issue by Muriano** [freepik-company/gommitizen#15]
The way we calculate tag prefix now (we take value from current dir) can generate collisions when we have complex folder structures like:

```
images/
    php81/
        cli/
            .version.json
        web/
            .version.json
    php82/
        cli/
            .version.json
        web/
            .version.json
```

This folder struc, that in actually real, create 2 pairs of tags prefixed with cli and web.

I suggest to provide a way to configure custom prefixes for each .version.json file.

**Comment by sergiotejon** [comment]
Is this feature already implemented with our current --prefix flag? I ask this to close this is issue if it's done. @Muriano

**Comment by sergiotejon** [comment]
This could be similar to #48 @jaimeph
