### ISSUE TITLE
Don't show a label description when the output of a hook is empty...

### ISSUE THREAD

**Issue by sergiotejon** [freepik-company/gommitizen#55]
... show a message like

```
Hook post-bump run
```

instead of 

```
Hook post-bump output:
```

This will be a cleaner output message in the `gommitizen bump` command.

**Comment by jaimeph** [comment]
Si no tiene hook no aparece ningún mensaje. Pero si usas --debug, debe aparecer un mensaje de "Sin hook o no hook".

**Comment by sergiotejon** [comment]
> Si no tiene hook no aparece ningún mensaje. Pero si usas --debug, debe aparecer un mensaje de "Sin hook o no hook".

Este caso ya estaba cubierto
```	hook, ok := v.Hooks[hookName]
	if !ok {
		slog.Debug(fmt.Sprintf("hook %s not found", hookName))
		return nil
	}
```
