### ISSUE TITLE
Actualizar README.md

### ISSUE THREAD

**Issue by jaimeph** [freepik-company/gommitizen#57]
Automatizar la ayuda del comando para ponerla en el README.md.
Actualizar el ejemplo de estructura de .version.json

**Comment by sergiotejon** [comment]
Creado generador de documentación mediante plantilla. Primera versión preliminar.

Genera el fichero README desde una plantilla incorporando las variables de descripción larga del commando raíz de la aplicación y luego incorpora de forma ordenada los diferentes comandos (bump, init y get) especificando difererentes subcomandos, ejemplos y flags.
